### ISSUE TITLE
Migrate to tailwind CSS and make it look better.

### ISSUE THREAD

**Issue by vinitvijal** [Prakhar9450/getyourfunds#1]
<img width="1440" alt="Screenshot 2024-02-14 at 10 12 08 AM" src="https://github.com/Prakhar9450/Random_Password_Generator/assets/77373310/e268c342-ccda-4a5a-9e11-d381f54441d8">

**Comment by vinitvijal** [comment]
@Prakhar9450 Please assign this to me.

**Comment by Prakhar9450** [comment]
@vinitvijal  Sorry to say but I would like to do it myself...
